In this assignement, feel free to use the `sparse` module from `scipy`.

Use the cell below for your imports.

In [18]:
import numpy as np
from scipy import sparse
from scipy.sparse import coo_matrix, csr_matrix
from scipy.sparse.linalg import spsolve

implement the function `mat_mul_coo` that takes two sparse matrices in `coo` and returns their product.

In [7]:
def mat_mul_coo(a, b):
    # Make sure the matrices are in COO format
    a = a.tocoo()
    b = b.tocoo()

    # Check if the dimensions are compatible for matrix multiplication
    if a.shape[1] != b.shape[0]:
        raise ValueError("Matrix dimensions do not match for multiplication")

    # Compute the product of the two matrices using the built-in dot function
    c = a.dot(b).tocoo()

    return c


In [8]:
a = coo_matrix(np.array([[1, 2, 0], [0, 3, 4], [5, 0, 6]]))
print(type(a))
print('--------------')
b = coo_matrix(np.array([[7, 0, 8], [0, 9, 10], [11, 0, 12]]))
print(type(b))
print('--------------')
c = mat_mul_coo(a, b)
print(type(c))
print('--------------')
print(c.toarray())


<class 'scipy.sparse.coo.coo_matrix'>
--------------
<class 'scipy.sparse.coo.coo_matrix'>
--------------
<class 'scipy.sparse.coo.coo_matrix'>
--------------
[[  7  18  28]
 [ 44  27  78]
 [101   0 112]]


In [9]:
A=[[1, 2, 0], [0, 3, 4], [5, 0, 6]]
print(type(A))
print('--------------')
B=[[7, 0, 8], [0, 9, 10], [11, 0, 12]]
print(type(B))
print('--------------')
C= np.dot(A,B)
print(type(C))
print('--------------')
print(C)

<class 'list'>
--------------
<class 'list'>
--------------
<class 'numpy.ndarray'>
--------------
[[  7  18  28]
 [ 44  27  78]
 [101   0 112]]


implement the function `mat_mul_csr` that takes two sparse matrices in `csr` format and returns their product.

In [12]:
from scipy.sparse import csr_matrix

def mat_mul_csr(A, B):
    # Make sure the matrices are in CSR format
    A = csr_matrix(A)
    B = csr_matrix(B)

    # Check if the dimensions are compatible for matrix multiplication
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrix dimensions do not match for multiplication")

    # Compute the product of the two matrices using the built-in dot function
    C = A.dot(B)

    return C


In [15]:
a = csr_matrix(np.array([[1, 2, 0], [0, 3, 4], [5, 0, 6]]))
print(type(a))
print('--------------')
b = csr_matrix(np.array([[7, 0, 8], [0, 9, 10], [11, 0, 12]]))
print(type(b))
print('--------------')
c = mat_mul_csr(a, b)
print(type(c))
print('--------------')
print(c.toarray())

<class 'scipy.sparse.csr.csr_matrix'>
--------------
<class 'scipy.sparse.csr.csr_matrix'>
--------------
<class 'scipy.sparse.csr.csr_matrix'>
--------------
[[  7  18  28]
 [ 44  27  78]
 [101   0 112]]


implement a function `solve_lin_sys` that takes a matrix `A` in `csr` format and a vector `b` as a numpy array and solves the system `Ax = b`.

In [16]:
def solve_lin_sys(A: csr_matrix, b: np.ndarray) -> np.ndarray:
    if A.shape[0] != A.shape[1] or A.shape[0] != b.shape[0]:
        raise ValueError("Invalid dimensions for A and b")

    x = spsolve(A, b)
    return x


In [19]:
A = csr_matrix([[3, 0, 1], [0, 2, 0], [1, 0, 1]])
b = np.array([1, 2, 3])
x = solve_lin_sys(A, b)
print(x)

[-1.  1.  4.]
